RAILS_APP_URLY_TINY_urlshortener/config/routes.rb
UrlyTiny::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'link_stats', to: 'users#show', as: 'link_stats'


  resources :users, :except => [:destroy, :edit, :update, :index, :show]
  resources :sessions, :except => [:edit, :update, :index,:show]

  resources :urls, :except => [:destroy, :edit, :update, :new]
  # resources :visits, :only => [:show]
  get '/:id', :to => 'visits#show'


  root :to => 'urls#index'
end

RAILS_APP_URLY_TINY_urlshortener/app/models/url.rb
class Url < ActiveRecord::Base

  has_many :visits
  after_create :shorten_url
  validates_presence_of :original_url
  belongs_to :user

private

  def shorten_url
    update(:shortened_url => id)
  end
end

RAILS_APP_URLY_TINY_urlshortener/app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  has_secure_password
  has_many :urls

end

RAILS_APP_URLY_TINY_urlshortener/app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :url
end

RAILS_APP_URLY_TINY_urlshortener/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  def current_user
    @curent_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

RAILS_APP_URLY_TINY_urlshortener/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/', notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/', notice: "Logged out"
  end
end

RAILS_APP_URLY_TINY_urlshortener/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    # :user_id => current_user.id
    @url.user_id = current_user.id
    if @url.save
      redirect_to url_path(@url.id)
    else 
      redirect_to '/', notice: "Please enter an entire URL."
    end
  end

  def show
    @url = Url.find(params[:id])
  end

private

  def url_params 
    params.require(:url).permit(:original_url)
  end
end

RAILS_APP_URLY_TINY_urlshortener/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/', notice: "thank you for signing up"
    else
      render "new"
    end
  end

  def show
    @urls = current_user.urls
  end
  

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

RAILS_APP_URLY_TINY_urlshortener/app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def show
    @url = Url.find(params[:id])
    Visit.create(:url_id => params[:id])
    redirect_to @url.original_url
  end
end

RAILS_APP_URLY_TINY_urlshortener/app/helpers/application_helper.rb
module ApplicationHelper
end

RAILS_APP_URLY_TINY_urlshortener/app/helpers/sessions_helper.rb
module SessionsHelper
end

RAILS_APP_URLY_TINY_urlshortener/app/helpers/users_helper.rb
module UsersHelper
end

RAILS_APP_URLY_TINY_urlshortener/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlyTiny</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "styles" %>
</head>
<body>
<%= flash[:notice] %>
<%= yield %>

</body>
</html>

RAILS_APP_URLY_TINY_urlshortener/app/views/urls/index.html.erb
<h1>URLYTINY!</h1>
<body>
  <div id="user_header">
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log Out", logout_path %>
      <%= link_to "View Link Stats", link_stats_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Log In", login_path %>
    <% end %>
  </div>




<%= form_for @url do |f|  %>
  <%= f.label :original_url  %>
  <%= f.text_field :original_url %>
  <%= f.hidden_field :user_id %>
  <%= f.submit %>
<% end %>

<% if @url.errors.any? %>
  <h3>Please correct these problems:</h3>
  <ul>
    <% @url.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

RAILS_APP_URLY_TINY_urlshortener/app/views/urls/show.html.erb
<h1> Your new shortened URL! </h1>
<div class="space">
</div>

<div class="shortTable">
  <a href="<%= request.base_url +  '/' + @url.shortened_url %>" target="_blank"><%= request.base_url + '/' + @url.shortened_url %></a>

  <p>This has been viewed <%= "#{@url.visits.count}" %> times.</p>
</div>

RAILS_APP_URLY_TINY_urlshortener/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
    <%= f.submit %>
<% end %>

RAILS_APP_URLY_TINY_urlshortener/app/views/users/show.html.erb
<h1> Link Stats </h1>

<ul style="list-style:none">
   <% @urls.each do |url| %>
    <li><%= url.original_url %></li>
    <li><%= request.base_url + '/' + url.shortened_url %></li>
  <% end %>
</ul>

<!-- add in short urls and a hrefs, plus eventually add in visits -->

RAILS_APP_URLY_TINY_urlshortener/app/views/visits/index.html.erb
<h1> Tiny Hit List </h1>

<%= @url.visits.count %>

RAILS_APP_URLY_TINY_urlshortener/app/views/visits/show.html.erb
<%= @url.original_url %>