RAILS_APP nerd_news (hacker news clone)/nerd_news/config/routes.rb
NerdNews::Application.routes.draw do
  resources :posts
  resources :users
  resources :sessions
  resources :votes

  get 'logout', to: 'sessions#destroy', as: 'logout'
  root :to => 'posts#index'
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  

  def Post.sort
    sorted_posts = self.all.sort_by do |post|
      post.votes.count
    end
    sorted_posts.reverse
  end

  def points
    age_in_hours = (Time.now - self.created_at) / 3600 + 1
    points = (self.votes.count / age_in_hours).round(1)
    # degrated_points = points * 0.5
    # points - degrated_points
  end
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/models/session.rb
class Session < ActiveRecord::Base
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username
  has_secure_password
  has_many :posts 
  has_many :votes
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :user_id, :scope => :post_id 
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Please Log In" if current_user.nil?
  end
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.new
    @posts = Post.all
    @vote = Vote.new
    @sort = Post.sort
  end

  def new 
    @post = Post.create(post_params)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @posts = Post.all
    if @post.save
      flash[:notice] = "Your post has been created"
      redirect_to "/"
    else render :new
    end
  end

  def show
    @post = Post.find(post_params[:id])
  end

private
  def post_params
    params.require(:post).permit(:link, :description)
  end

end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/', notice: "Logged In!"
    else
      flash.now.alert = "Username or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/', notice: "Logged Out"
  end
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 
    @user = User.new(:username => params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/', notice: "Thank you for signing up"
    else 
      render "new"
    end
  end

  def show
      @posts = current_user.posts
  end

private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/controllers/votes_controller.rb
class VotesController < ApplicationController


  def index
    @vote = Vote.new
  end

  def create
   @vote =  current_user.votes.new(vote_params)
    if @vote.save
      flash.alert = "thanks for voting"
      redirect_to posts_path
    else 
      redirect_to posts_path
    end
  end

private

  def vote_params
    params.require(:vote).permit(:post_id)
  end
end

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="text-align:center">
<head>
  <title>NerdNews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>
<%= yield %>

</body>
</html>

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/views/posts/index.html.erb
<h1> NERD NEWS </h1>


  <div id="user_header">
    <% if current_user %>
     <p> Logged in as <%= current_user.username %>.</p>
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      <%= link_to "Log In", new_session_path %>
    <% end %>
  </div>

  <div id="make_a_post">
    <% if current_user %>
      <%= form_for @post do |f| %>
        <%= f.label :description %>
        <%= f.text_field :description %>
        <%= f.text_field :link %>
        <%= f.submit %>
      <% end %>
    <% end %>
  <div>

  <ul style="list-style:none">
    <% @sort.each do |post| %>
      <li><%= link_to post.description, post.link %></li>
      <li>Posted by: <%= post.user.username %></li>
      <li><%= post.votes.count %> votes </li>
      <%= post.points %>
      <%= form_for @vote do |f| %>
        <%= f.hidden_field :post_id, :value => post.id %>
        <%= f.submit %>
      <% end %>
    <% end %>
  </ul>

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/views/posts/show.html.erb
<% post.link %>

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
    <%= f.submit %>
<% end %>

RAILS_APP nerd_news (hacker news clone)/nerd_news/app/views/votes/index.html.erb
<% posts_path %>